# Site Configuration
timezone: America/Sao_Paulo

title: Gustavo Ribeiro - Desenvolvedor frontend
description: Desenvolvedor Frontend, Wordpress e Fotógrafo :).
url: https://gustavoribeiro.com

permalink: /:categories/:title.html

highlighter: rouge

plugins:
  - jekyll-redirect-from
